



## spring security 配置
security:
  oauth2:
    client:
      client-id: chiyou
      client-secret: chiyou
      scope: server
    resource:
      token-info-uri: http://localhost:9999/auth/oauth/check_token

# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1qaz@WSX
    url: jdbc:mysql://clf-d-server:3306/ziya?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  rabbitmq:
    host: clf-rabbitmq.colourfulchina.com
    port: 5672
    username: admin
    password: 1qaz@WSX
  cloud:
    bus:
      refresh:
        enabled: true
      trace:
        enabled: true

#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.colourfulchina.chiyou.api.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    # 逻辑删除字段
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
